version: '3'
 
services:
  mariadb:
    image: mariadb:10.6.7
    container_name: mariadb_container
    restart: always
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=mariadb123
    - TZ=America/Argentina/Buenos_Aires
    volumes:
    - ./data/my.cnf:/etc/mysql/my.cnf
    - ./data/config:/var/lib/mysql